config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    $builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', 'Pages::display');

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $builder->fallbacks();
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *
 *     // Parse specified extensions from URLs
 *     // $builder->setExtensions(['json', 'xml']);
 *
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Item.php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Item Entity
 *
 * @property int $id
 * @property string $photo
 * @property string $name
 * @property int $id_category
 * @property int $id_owner
 * @property int $id_address
 * @property string $description
 * @property string $qr_code
 */
class Item extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'photo' => true,
        'name' => true,
        'id_category' => true,
        'id_owner' => true,
        'id_address' => true,
        'description' => true,
        'qr_code' => true,
    ];
}

src/Model/Table/ItemTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Item Model
 *
 * @method \App\Model\Entity\Item newEmptyEntity()
 * @method \App\Model\Entity\Item newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Item[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Item get($primaryKey, $options = [])
 * @method \App\Model\Entity\Item findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Item patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Item[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Item|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Item saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Item[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Item[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Item[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Item[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 */
class ItemTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('item');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->belongsTo('Category')->setForeignKey('id_category');
        $this->belongsTo('Users')->setForeignKey('id_address');
        //$this->belongsToMany('UserItem')->setForeignKey('id_address');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('photo')
            ->allowEmptyString('photo', 'create');

        $validator
            ->scalar('name')
            ->maxLength('name', 200)
            ->requirePresence('name', 'create')
            ->notEmptyString('name');

        $validator
            ->integer('id_category')
            ->requirePresence('id_category', 'create')
            ->notEmptyString('id_category');

        $validator
            ->integer('id_owner')
            ->requirePresence('id_owner', 'create')
            ->notEmptyString('id_owner');

        $validator
            ->integer('id_address')
            ->requirePresence('id_address', 'create')
            ->notEmptyString('id_address');

        $validator
            ->scalar('description')
            ->requirePresence('description', 'create')
            ->notEmptyString('description');

        return $validator;
    }
}

src/Controller/ItemController.php
<?php
declare(strict_types=1);

namespace App\Controller;

/**
 * Item Controller
 *
 * @property \App\Model\Table\ItemTable $Item
 * @method \App\Model\Entity\Item[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ItemController extends AppController
{
	/**
	 * Index method
	 *
	 * @return \Cake\Http\Response|null|void Renders view
	 */
	public function index()
	{
        $this->paginate = [
            'contain' => ['Category', 'Users']
        ];

		$this->set('item', $this->paginate($this->Item));
	}

	/**
	 * View method
	 *
	 * @param string|null $id Item id.
	 * @return \Cake\Http\Response|null|void Renders view
	 * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
	 */
	public function view($id = null)
	{
		$item = $this->Item->get($id, [
			'contain' => ['Category', 'Users']
		]);

        $this->set(compact('item'));
	}

	/**
	 * Add method
	 *
	 * @return \Cake\Http\Response|null|void Redirects on successful add, renders view otherwise.
	 */
	public function add()
	{
		$item = $this->Item->newEmptyEntity();

		$userTable = $this->getTableLocator()->get('Users');
        $userContent = $userTable->find('all');
        $users = $userContent->toArray();
        $this->set(compact('users'));

		$categoryTable = $this->getTableLocator()->get('Category');
        $categoryContent = $categoryTable->find('all');
        $categories = $categoryContent->toArray();
        $this->set(compact('categories'));

		if ($this->request->is('post')) {
			$file = $this->request->getData('photo');
			if ($file->getClientFilename() == ''){
                $this->Flash->error(__('Vous devez ajouter une image.'));
			}
			else {
				$targetPath = WWW_ROOT."img".DS."Items".DS.$file->getClientFilename();
				$file->moveTo($targetPath);
				$newItem = $this->request->getData();
				$newItem['photo'] =  "Items".DS.$file->getClientFilename();
				$item = $this->Item->patchEntity($item, $newItem);
				if ($this->Item->save($item)) {
					$this->Flash->success(__('Le matériel a été enregistré.'));

					return $this->redirect(['action' => 'index']);
				}
				$this->Flash->error(__('Le matériel n\'a pas pu être enregistré. Veuillez réessayer.'));
			}
		}
		$this->set(compact('item'));
	}

	/**
	 * Edit method
	 *
	 * @param string|null $id Item id.
	 * @return \Cake\Http\Response|null|void Redirects on successful edit, renders view otherwise.
	 * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
	 */
	public function edit($id = null)
	{
		$item = $this->Item->get($id, [
			'contain' => [],
		]);

		$userTable = $this->getTableLocator()->get('Users');
        $userContent = $userTable->find('all');
        $users = $userContent->toArray();
        $this->set(compact('users'));

		$categoryTable = $this->getTableLocator()->get('Category');
        $categoryContent = $categoryTable->find('all');
        $categories = $categoryContent->toArray();
        $this->set(compact('categories'));
		
		if ($this->request->is(['patch', 'post', 'put'])) {
			$file = $this->request->getData('photo');
			if ($file->getClientFilename() == ''){
                $newItem = $this->request->getData();
                $newItem['photo'] =  $item['photo'];
				$item = $this->Item->patchEntity($item, $newItem);
				if ($this->Item->save($item)) {
					$this->Flash->success(__('Le matériel a été enregistré.'));

					return $this->redirect(['action' => 'index']);
				}
				$this->Flash->error(__('Le matériel n\'a pas pu être enregistré. Veuillez réessayer.'));
			} else {
				$targetPath = WWW_ROOT."img".DS."Items".DS.$file->getClientFilename();
				$file->moveTo($targetPath);
				$newItem = $this->request->getData();
				$newItem['photo'] =  "Items".DS.$file->getClientFilename();
				$item = $this->Item->patchEntity($item, $newItem);
				if ($this->Item->save($item)) {
					$this->Flash->success(__('Le matériel a été enregistré.'));
					return $this->redirect(['action' => 'index']);
				}
				$this->Flash->error(__('Le matériel n\'a pas pu être enregistré. Veuillez réessayer.'));
			}
		}
		$this->set(compact('item'));
	}

	/**
	 * Delete method
	 *
	 * @param string|null $id Item id.
	 * @return \Cake\Http\Response|null|void Redirects to index.
	 * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
	 */
	public function delete($id = null)
	{
		$this->request->allowMethod(['post', 'delete']);
		$item = $this->Item->get($id);
		if ($this->Item->delete($item)) {
			$this->Flash->success(__('Le matériel a été supprimé.'));
		} else {
			$this->Flash->error(__('Le matériel n\'a pas pu être supprimé. Veuillez réessayer.'));
		}

		return $this->redirect(['action' => 'index']);
	}

    /**
     * Loan method
     *
     * @param string|null $id Item id.
     * @return \Cake\Http\Response|null|void Redirects on successful loan, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function loan($id = null)
    {
        $item = $this->Item->get($id, [
            'contain' => [],
        ]);
        $uid = $_SESSION['Auth']['id'];
        $item['id_address'] = $uid;

        $item = $this->Item->patchEntity($item, $this->request->getData());
        if ($this->Item->save($item)) {
            $this->Flash->success(__('Le matériel a été emprunté.'));
            return $this->redirect(['action' => 'list']);
        }
        $this->Flash->error(__('Le matériel n\'a pas pu être emprunté. Veuillez réessayer.'));

        $this->set(compact('item'));
    }

	/**
     * Return method
     *
     * @param string|null $id Item id.
     * @return \Cake\Http\Response|null|void Redirects on successful loan, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function return($id = null)
    {
        $item = $this->Item->get($id, [
            'contain' => [],
        ]);

        $item['id_address'] = $item['id_owner'];

        $item = $this->Item->patchEntity($item, $this->request->getData());
        if ($this->Item->save($item)) {
            $this->Flash->success(__('Le matériel a été rendu.'));
            return $this->redirect(['action' => 'list']);
        }
        $this->Flash->error(__('Le matériel n\'a pas pu être rendu. Veuillez réessayer.'));

        $this->set(compact('item'));
    }

	/**
     * List method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function list()
    {
		$uid = $_SESSION['Auth']['id'];
		$this->paginate = [
            'contain' => ['Category', 'Users']

        ];
		$this->set('item', $this->paginate($this->Item));

        $query = $this->Item->find('all')
			->where(['Item.id_address' => $uid]);
		foreach ($query as $row) {
		}
		$results = $query->all();
		$data = $results->toArray();

		$this->set(compact('data'));
    }
}

templates/Item/add.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Item $item
 */
?>
<div class="row">
    <aside class="column">
        <div class="side-nav">
            <h4 class="heading"><?= __('Actions') ?></h4>
            <?= $this->Html->link(__('Lister les matériels'), ['action' => 'index'], ['class' => 'side-nav-item']) ?>
        </div>
    </aside>
    <div class="column-responsive column-80">
        <div class="formclass">
            <?= $this->Form->create($item, ['type' => 'file']) ?>
            <fieldset>
                <legend><?= __('Ajouter un matériel') ?></legend>
                <?php
                    echo $this->Form->control('photo', ['type' => 'file', 'label' => 'Photo']);
                    echo $this->Form->control('name', ['label' => 'Nom']);
                    ?>
                    <div class="input select">
                        <label for="id_category">Catégorie</label>
                        <select name="id_category" id="id_category">
                        <?php
                        foreach ($categories as $category): ?>
                            <option name=<?= $category->name ?> value=<?= $category->id ?>><?= $category->name ?></option>
                        <?php endforeach ?>
                        </select>          
                    </div>

                    <div class="input select">
                        <label for="id_owner">Propriétaire</label>
                        <select name="id_owner" id="id_owner">
                        <?php
                        foreach ($users as $user): ?>
                            <option name=<?= $user->first_name ?> value=<?= $user->id ?>><?= $user->first_name ?> <?= $user->last_name ?></option>
                        <?php endforeach ?>
                        </select>          
                    </div>

                    <div class="input select">
                        <label for="id_address">Adresse où le matériel est stocké</label>
                        <select name="id_address" id="id_address">
                        <?php
                        foreach ($users as $user): ?>
                            <option name=<?= $user->address ?> value=<?= $user->id ?>><?= $user->first_name ?> <?= $user->last_name ?>
                            <?= $user->address ?> <?= $user->zip_code?> <?= $user->city ?></option>
                        <?php endforeach ?>
                        </select>          
                    </div>
                    <?php
                    echo $this->Form->control('description', ['label' => 'Description']);
                ?>
            </fieldset>
            <?= $this->Form->button(__('Ajouter')) ?>
            <?= $this->Form->end() ?>
        </div>
    </div>
</div>

templates/Item/edit.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Item $item
 */
?>
<div class="row">
    <aside class="column">
        <div class="side-nav">
            <h4 class="heading"><?= __('Actions') ?></h4>
            <?= $this->Form->postLink(
                __('Supprimer'),
                ['action' => 'delete', $item->id],
                ['confirm' => __('Êtes vous sûr de vouloir supprimer {0}?', $item->name), 'class' => 'side-nav-item']
            ) ?>
            <?= $this->Html->link(__('Lister les matériels'), ['action' => 'index'], ['class' => 'side-nav-item']) ?>
        </div>
    </aside>
    <div class="column-responsive column-80">
        <div class="formclass">
            <?= $this->Form->create($item, ['type' => 'file']) ?>
            <fieldset>
                <legend><?= __('Modifier le matériel') ?></legend>
                <?php
                    echo $this->Form->control('photo', ['type' => 'file', 'label' => 'Photo']);
                    echo $this->Form->control('name', ['label' => 'Nom']);
                    ?>
                    <div class="input select">
                        <label for="id_category">Catégorie</label>
                        <select name="id_category" id="id_category">
                        <?php
                        foreach ($categories as $category): ?>
                            <option name=<?= $category->name ?> value=<?= $category->id ?>><?= $category->name ?></option>
                        <?php endforeach ?>
                        </select>          
                    </div>

                    <div class="input select">
                        <label for="id_owner">Propriétaire</label>
                        <select name="id_owner" id="id_owner">
                        <?php
                        foreach ($users as $user): ?>
                            <option name=<?= $user->first_name ?> value=<?= $user->id ?>><?= $user->first_name ?> <?= $user->last_name ?></option>
                        <?php endforeach ?>
                        </select>          
                    </div>

                    <div class="input select">
                        <label for="id_address">Adresse où le matériel est stocké</label>
                        <select name="id_address" id="id_address">
                        <?php
                        foreach ($users as $user): ?>
                            <option name=<?= $user->address ?> value=<?= $user->id ?>><?= $user->first_name ?> <?= $user->last_name ?>
                            <?= $user->address ?> <?= $user->zip_code?> <?= $user->city ?></option>
                        <?php endforeach ?>
                        </select>          
                    </div>
                    <?php
                    echo $this->Form->control('description', ['label' => 'Description']);
                ?>
            </fieldset>
            <?= $this->Form->button(__('Modifier')) ?>
            <?= $this->Form->end() ?>
        </div>
    </div>
</div>

templates/Item/index.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Item[]|\Cake\Collection\CollectionInterface $item
 */
?>
<div class="item index content">
    <?= $this->Html->link(__('Ajouter un matériel'), ['action' => 'add'], ['class' => 'button float-right']) ?>
    <h3><?= __('Liste du matériel') ?></h3>
    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th class="actions">_____________</th>
                    <th class="actions">Libellé</th>
                    <th class="actions">Catégorie</th>
                    <th class="actions">Propriétaire</th>
                    <th class="actions">Adresse</th>
                    <th class="actions"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($item as $item): ?>
                <tr>
                    <td><?= $this->Html->image($item->photo) ?></td>
                    <td><?= h($item->name) ?></td>
                    <td><?= h($item->category->name) ?></td>
                    <td><?= h($item->user->last_name) ?> <?= h($item->user->first_name) ?></td>
                    <td><?=h($item->user->last_name)?> <?=h($item->user->first_name)?> <br/>
                        <?= h($item->user->address)?> <br/>
                        <?= h($item->user->zip_code)?> <?=h($item->user->city)?></td>
                    <td class="actions">
                        <?= $this->Html->link(__('Afficher'), ['action' => 'view', $item->id]) ?>
                        <?= $this->Html->link(__('Emprunter'), ['action' => 'loan', $item->id], ['confirm' => __('Êtes vous sûr de vouloir emprunter {0}?', $item->name)]) ?>
                        <?= $this->Html->link(__('Modifier'), ['action' => 'edit', $item->id]) ?>
                        <?= $this->Form->postLink(__('Supprimer'), ['action' => 'delete', $item->id], ['confirm' => __('Êtes vous sûr de vouloir supprimer {0}?', $item->name)]) ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('Précédent')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('Suivant') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(__('Page {{page}} sur {{pages}}, affichage de {{current}} enregistrements sur {{count}} au total')) ?></p>
    </div>
</div>

templates/Item/list.php
<?php 
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Item[]|\Cake\Collection\CollectionInterface $item
 */
?>
<div class="item index content">
    <?= $this->Html->link(__('Emprunter du matériel'), ['action' => 'index'], ['class' => 'button float-right']) ?>
    <h3><?= __('Liste du matériel emprunté') ?></h3>
    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th><?= $this->Paginator->sort('') ?></th>
                    <th><?= $this->Paginator->sort('Matériel') ?></th>
                    <th><?= $this->Paginator->sort('Catégorie') ?></th>
                    <th><?= $this->Paginator->sort('Propriétaire') ?></th>
                    <th class="actions"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data as $data): ?>
                <tr>
                    <td><?= $this->Html->image($data->photo) ?></td>
                    <td><?= h($data->name) ?></td>
                    <td><?= h($item->first()->category->name) ?></td>
                    <td><?= h($item->first()->user->last_name) ?> <?= h($item->first()->user->first_name) ?></td>
                    <td class="actions">
                        <?= $this->Html->link(__('Rendre le matériel'), ['action' => 'return', $data->id], ['confirm' => __('Êtes vous sûr de vouloir rendre {0}?', $data->name)]) ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('Précédent')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('Suivant') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
    </div>
</div>

templates/Item/view.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Item $item
 */
?>
<div class="row">
    <aside class="column">
        <div class="side-nav">
            <h4 class="heading"><?= __('Actions') ?></h4>
            <?= $this->Html->link(__('Modifier le matériel'), ['action' => 'edit', $item->id], ['class' => 'side-nav-item']) ?>
            <?= $this->Form->postLink(__('Supprimer le matériel'), ['action' => 'delete', $item->id], ['confirm' => __('Êtes vous sûr de vouloir supprimer {0}?', $item->name), 'class' => 'side-nav-item']) ?>
            <?= $this->Html->link(__('Lister les matériels'), ['action' => 'index'], ['class' => 'side-nav-item']) ?>
            <?= $this->Html->link(__('Ajouter un matériel'), ['action' => 'add'], ['class' => 'side-nav-item']) ?>
            <?= $this->Html->link(__('Emprunter le matériel'), ['action' => 'loan', $item->id], ['confirm' => __('Êtes vous sûr de vouloir emprunter {0}?', $item->name),'class' => 'side-nav-item']) ?>
        </div>
    </aside>
    <div class="column-responsive column-80">
        <div class="item view content">
            <h3><?= h($item->name) ?></h3>
            <table>
                <tr class="text">
                    <th><?= __('') ?></th>
                    <td><?= $this->Html->image($item->photo, ['class' => 'picture-view']) ?></td>
                </tr>
                <tr>
                    <th><?= __('Libellé') ?></th>
                    <td><?= h($item->name) ?></td>
                </tr>
                <tr>
                    <th><?= __('Catégorie du matériel') ?></th>
                    <td><?= h($item->category->name) ?></td>
                </tr>
                <tr>
                    <th><?= __('Propriétaire du matériel') ?></th>
                    <td> <?= h($item->user->last_name) ?> <?= h($item->user->first_name) ?></td>
                </tr>
                <tr>
                    <th><?= __('L\'adresse où se situe le matériel') ?></th>
                    <td> <?=h($item->user->last_name)?> <?=h($item->user->first_name)?> <br/>
                    <?= h($item->user->address)?> <br/>
                    <?= h($item->user->zip_code)?> <?=h($item->user->city)?> </td>

                </tr>
            </table>
            <div class="text">
                <strong><?= __('Description') ?></strong>
                <blockquote>
                    <?= $this->Text->autoParagraph(h($item->description)); ?>
                </blockquote>
            </div>
        </div>
    </div>
</div>